on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
    name: Build and Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p build/
      - run: echo hello > build/world.txt
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: build/world.txt      
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          name: business-card
      - name: Publish
        run: |
          cat build/world.txt
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm ci
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release Notes
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.ref }}",
              generate_release_notes: true
            });
