on:
  push:
    tags:
      - 'v*'

name: Build, Publish, Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: Add wasm32-unknown-emscripten Target
        run: rustup target add wasm32-unknown-emscripten
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 2.0.0
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Build
        run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: card
          path: |
            ./*.js
            ./*.json
            ./card.wasm
            LICENSE
            README.md
  dry-run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: card
      - name: Publish
        uses: MetaMask/action-npm-publish@57b69dd5b3dedb766838676528624ecb93390a26
  publish:
    environment: publish
    runs-on: ubuntu-latest
    needs: dry-run
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: card
      - name: Publish
        uses: MetaMask/action-npm-publish@57b69dd5b3dedb766838676528624ecb93390a26
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

  github-release:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release Notes
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.ref }}",
              generate_release_notes: true
            });
