on:
  push:
    tags:
      - 'v*'

name: Build and Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: Add WASM Target
        run: |
          rustup target add wasm32-unknown-emscripten
      - name: setup emsdk
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          git pull
          ./emsdk install 2.0.0
          ./emsdk activate 2.0.0
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Build
        run: |
          git --version
          cargo --version
          yarn --version
          source ./emsdk/emsdk_env.sh
          emsdk list
          yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: card
          path: |
            ./bin.js
            ./card.js
            ./card.wasm
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - uses: actions/download-artifact@v2
        with:
          name: card
      - name: Publish
        run: |
          yarn start
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm ci
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release Notes
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.ref }}",
              generate_release_notes: true
            });
